// <auto-generated />
namespace TP_2_Restaurant.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddViewBag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddViewBag));
        
        string IMigrationMetadata.Id
        {
            get { return "201804062000292_AddViewBag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
