// <auto-generated />
namespace TP_2_Restaurant.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CedEtDom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CedEtDom));
        
        string IMigrationMetadata.Id
        {
            get { return "201804121721384_CedEtDom"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
